badwords:
  - fuck
  - shit
  - fuk
  - cunt
  - piss
  - asshole
  - dick
  - penis
  - vagina
  - pussy
  - poontang
  - cum
  - mustang
  - f u c k
  - s h i t
  - f u k
replacement: My breath smells like cat food!